import {
  Activity,
  Bot,
  Boxes,
  Braces,
  Brain,
  Cloud,
  Code2,
  Container,
  Cpu,
  Cylinder,
  Database,
  Gauge,
  GitBranch,
  Hexagon,
  Layout,
  Layers,
  Link2,
  Network,
  Radio,
  Search,
  Server,
  Share2,
  ShieldCheck,
  Sparkles,
  Wallet,
  Webhook,
  Workflow,
  Zap,
} from 'lucide-react'

const MAP = {
  activity: Activity,
  bot: Bot,
  boxes: Boxes,
  brain: Brain,
  cloud: Cloud,
  code2: Code2,
  container: Container,
  cpu: Cpu,
  cylinder: Cylinder,
  database: Database,
  gauge: Gauge,
  gitBranch: GitBranch,
  hexagon: Hexagon,
  layout: Layout,
  layers: Layers,
  link: Link2,
  network: Network,
  radio: Radio,
  rust: Braces,
  search: Search,
  server: Server,
  share2: Share2,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  wallet: Wallet,
  webhook: Webhook,
  workflow: Workflow,
  zap: Zap,
}

export function SkillIcon({ iconKey, className, strokeWidth = 1.25 }) {
  const Cmp = MAP[iconKey] || Layout
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden />
}
